# SPDX-License-Identifier: MIT
cmake_minimum_required(VERSION 3.20.0)

set(DTC_OVERLAY_FILE ${CMAKE_CURRENT_SOURCE_DIR}/../../boards/xiao_ble_nrf52840.overlay)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})
project(little_on_air_controller)

include(${CMAKE_CURRENT_SOURCE_DIR}/../../cmake/loa-common.cmake)

target_sources(app PRIVATE
  src/ble_client.c
  src/main.c
)

target_include_directories(app PRIVATE src)
