[platformio]
default_envs = xiao_esp32s3

[env:xiao_esp32s3]
platform = espressif32@6.12.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 460800
extra_scripts = pre:shared_sources.py
    pre:nimble_guard.py
lib_deps =
    h2zero/NimBLE-Arduino@2.5.1
    adafruit/Adafruit SSD1306@2.5.15
    adafruit/Adafruit NeoPixel@1.15.2
    adafruit/Adafruit GFX Library@1.12.6
    adafruit/Adafruit BusIO@1.17.4
build_flags =
    -I ../../include
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -D CONFIG_BT_NIMBLE_MAX_BONDS=1
    -D CONFIG_BT_NIMBLE_MAX_CCCDS=2
    -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
    -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER=0
    -D MYNEWT_VAL_BLE_SM_LEGACY=0
    -D LOA_ENCODER_DIRECTION=1
